### ISSUE TITLE
java.lang.NoClassDefFoundError: com.squareup.otto.Bus on Android Gradle plugin 1.0

### ISSUE THREAD

**Issue by anisart** [square/otto#141]
I update my IDE IDEA to version 14.0.3. Then update Android Gradle plugin to 1.0 and Gradle to 2.2.1.
Project build successful but while starting application crashes with log (API 19):

```
02-02 12:10:47.862  23673-23673/ru.gnivc.lkip.local246 W/dalvikvm﹕ VFY: unable to find class referenced in signature (Lcom/squareup/otto/Bus;)
02-02 12:10:47.862  23673-23673/ru.gnivc.lkip.local246 I/dalvikvm﹕ Could not find method com.squareup.otto.Bus.register, referenced from method ru.gnivc.lkip.LkipApp.onCreate
02-02 12:10:47.862  23673-23673/ru.gnivc.lkip.local246 W/dalvikvm﹕ VFY: unable to resolve virtual method 259: Lcom/squareup/otto/Bus;.register (Ljava/lang/Object;)V
02-02 12:10:47.862  23673-23673/ru.gnivc.lkip.local246 D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0027
02-02 12:10:47.862  23673-23673/ru.gnivc.lkip.local246 E/dalvikvm﹕ Could not find class 'com.squareup.otto.Bus', referenced from method ru.gnivc.lkip.BusProvider.<clinit>
02-02 12:10:47.862  23673-23673/ru.gnivc.lkip.local246 W/dalvikvm﹕ VFY: unable to resolve new-instance 123 (Lcom/squareup/otto/Bus;) in Lru/gnivc/lkip/BusProvider;
02-02 12:10:47.862  23673-23673/ru.gnivc.lkip.local246 D/dalvikvm﹕ VFY: replacing opcode 0x22 at 0x0000
02-02 12:10:47.872  23673-23673/ru.gnivc.lkip.local246 W/dalvikvm﹕ VFY: unable to find class referenced in signature (Lcom/squareup/otto/Bus;)
02-02 12:10:47.872  23673-23673/ru.gnivc.lkip.local246 D/dalvikvm﹕ DexOpt: unable to opt direct call 0x0101 at 0x05 in Lru/gnivc/lkip/BusProvider;.<clinit>
02-02 12:10:47.872  23673-23673/ru.gnivc.lkip.local246 W/dalvikvm﹕ Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lru/gnivc/lkip/BusProvider;
02-02 12:10:47.872  23673-23673/ru.gnivc.lkip.local246 D/AndroidRuntime﹕ Shutting down VM
02-02 12:10:47.872  23673-23673/ru.gnivc.lkip.local246 W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x4165ece0)
02-02 12:10:47.872  23673-23673/ru.gnivc.lkip.local246 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: ru.gnivc.lkip.local246, PID: 23673
    java.lang.NoClassDefFoundError: com.squareup.otto.Bus
            at ru.gnivc.lkip.BusProvider.<clinit>(BusProvider.java:11)
            at ru.gnivc.lkip.LkipApp.<init>(LkipApp.java:14)
            at java.lang.Class.newInstanceImpl(Native Method)
            at java.lang.Class.newInstance(Class.java:1208)
            at android.app.Instrumentation.newApplication(Instrumentation.java:990)
            at android.app.Instrumentation.newApplication(Instrumentation.java:975)
            at android.app.LoadedApk.makeApplication(LoadedApk.java:509)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4446)
            at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
            at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
            at android.app.ActivityThread.handleBindApplication(Native Method)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
```

On API 21 too:
```
02-02 12:39:35.871    3920-3920/ru.gnivc.lkip.local246 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: ru.gnivc.lkip.local246, PID: 3920
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/otto/Bus;
            at ru.gnivc.lkip.BusProvider.<clinit>(BusProvider.java:11)
            at ru.gnivc.lkip.LkipApp.<init>(LkipApp.java:14)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.Class.newInstance(Class.java:1572)
            at android.app.Instrumentation.newApplication(Instrumentation.java:994)
            at android.app.Instrumentation.newApplication(Instrumentation.java:979)
            at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4491)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.otto.Bus" on path: DexPathList[[zip file "/data/app/ru.gnivc.lkip.local246-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at ru.gnivc.lkip.BusProvider.<clinit>(BusProvider.java:11)
            at ru.gnivc.lkip.LkipApp.<init>(LkipApp.java:14)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.Class.newInstance(Class.java:1572)
            at android.app.Instrumentation.newApplication(Instrumentation.java:994)
            at android.app.Instrumentation.newApplication(Instrumentation.java:979)
            at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4491)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
    Suppressed: java.lang.ClassNotFoundException: com.squareup.otto.Bus
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 18 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by anisart** [comment]
Sorry, cleaning project resolve this issue)
