### ISSUE TITLE
Is Bus.register() meant to be threadsafe?

### ISSUE THREAD

**Issue by ppiech** [square/otto#148]
We're using it with the assumption it is, but seeing the following NPE:

Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.isEmpty()' on a null object reference
       at com.squareup.otto.AnnotatedHandlerFinder.findAllProducers(AnnotatedHandlerFinder.java:129)
       at com.squareup.otto.HandlerFinder$1.findAllProducers(HandlerFinder.java:33)
       at com.squareup.otto.Bus.register(Bus.java:191)
       ....

Looking at the thread it appears that access to the static method caches PRODUCERS_CACHE and SUBSCRIBERS_CACHE is not synchronized in any way.

Thanks,
Pawel

**Comment by JakeWharton** [comment]
Thread safety was removed when we constrained the bus to the main thread. After exposing the ability to relax the main thread confinement the safety was never added back.

**Comment by ppiech** [comment]
Makes sense.  So do you consider it a bug and something addressed in the future, or just a limitation.  I assume I can work around it by synchronizing around registration/unregistration (as long as events are not emitted as a side effect).

**Comment by JakeWharton** [comment]
Yes, we should make it safe.

**Comment by JakeWharton** [comment]
A fix was merged.
