### ISSUE TITLE
ArrayIndexOutOfBoundsError in Bus

### ISSUE THREAD

**Issue by SafetyMarcus** [square/otto#152]
For a while now our app has been having crashes within the otto Bus file:

```java.lang.ArrayIndexOutOfBoundsException: length=0; index=1173229860
       at java.util.HashMap.addNewEntry(HashMap.java:476)
       at java.util.HashMap.put(HashMap.java:408)
       at com.squareup.otto.Bus.post(SourceFile:320)
       at com.example.myapp.asyncTask.doWakefulWork(SourceFile:56)
       at com.commonsware.cwac.wakeful.WakefulIntentService.onHandleIntent(SourceFile:106)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)```

My guess is that this is something to do with `Set<Class<?>> flattenHierarchy(Class<?> concreteClass)` as it is the only function I can see that would be being called that is modifying a `HashMap`

**Comment by tbsandee** [comment]
Looks like a thread-safety issue to me. The `flattenHierarchyCache` in `Otto.Bus` is not threadsafe (just a hashmap with no synchronization), so if you call `Bus.post()` from multiple threads there is potential for corruption internally. I think that's arguably a bug, because the javadocs imply that you are allowed to relax the main thread restrictions if you want. It doesn't explicitly say that `Otto.Bus` is threadsafe though, and if you use your bus instance from a single thread (main, or other) it should work fine.

`IntentService.onHandleIntent()` is called from a worker thread, not the main thread and calls to `Bus.post()` would typically be called from the main thread in simpler use cases.

When you create your Otto instance you might consider keeping the `ThreadEnforcer.MAIN` policy and fixing up your code to use the main thread for Otto interactions. It's closer to what most people will do, although the docs aren't 100% clear on the threadsafety of the various methods.

**Comment by tbsandee** [comment]
FYI, see PR #154. I think multithreaded access to Otto is discouraged, but since the APIs allow it it seems like a safe fix with little to no real-world performance degradation.
