### ISSUE TITLE
Error with Facebook SDK 4.0 in Android 4.4

### ISSUE THREAD

**Issue by ruschoni02** [square/otto#170]
I'm using the Facebook SDK 4.0 and not LOLIPOP THIS properly working, but I'll run When any Android 4.4 or Less That of 5.0 will not run and shows huge THAT LogCat

10-20 09:37:59.024  30129-30129/com.example.r2ttecnologia.projeto5_app E/AndroidRuntime﹕ FATAL EXCEPTION: main
Process: com.example.r2ttecnologia.projeto5_app, PID: 30129
java.lang.NoClassDefFoundError: com.example.r2ttecnologia.projeto5_app.MainFragment$1
        at com.example.r2ttecnologia.projeto5_app.MainFragment.onCreate(MainFragment.java:98)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:1939)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:988)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1572)
        at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:511)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1174)
        at android.app.Activity.performStart(Activity.java:5274)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:5299)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
Given the information provided, this has nothing to do with Otto.
