### ISSUE TITLE
NoClassDefFoundError when running in Android OS below 5.0.

### ISSUE THREAD

**Issue by ChrashTest** [square/otto#185]
Hi Team,

M creating an android application using Bus , it is working fine if its runs on Android  OS 5.0 and above but when we try to run it below 5.0, following exception is thrown.

java.lang.NoClassDefFoundError: com/example/events/FitnessUnauthorizedErrorEvent
            at java.lang.Class.getDeclaredMethods(Native Method)
            at java.lang.Class.getDeclaredMethods(Class.java:656)
            at com.squareup.otto.AnnotatedHandlerFinder.loadAnnotatedMethods(AnnotatedHandlerFinder.java:64)
            at com.squareup.otto.AnnotatedHandlerFinder.loadAnnotatedProducerMethods(AnnotatedHandlerFinder.java:49)
            at com.squareup.otto.AnnotatedHandlerFinder.findAllProducers(AnnotatedHandlerFinder.java:140)
            at com.squareup.otto.HandlerFinder$1.findAllProducers(HandlerFinder.java:33)
            at com.squareup.otto.Bus.register(Bus.java:190)
            at com.example.app.TestApplication.onCreate(TestApplication.java:58)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5165)
            at android.app.ActivityThread.access$1500(ActivityThread.java:156)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1418)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5883)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
            at dalvik.system.NativeStart.main(Native Method) .

Please advice how can we fix this issue.

**Comment by ChrashTest** [comment]
its fixed.

**Comment by tuanhs66** [comment]
Hi ChrashTest,
You've handled it happen.
Please help me!
Thanks!

**Comment by shanuka** [comment]
+1
